spring.datasource.url : jdbc:postgresql://172.17.0.1/vdms_dev
spring.datasource.username : root
spring.datasource.password : localhost
spring.datasource.driver-class-name : org.postgresql.Driver
spring.jpa.database :  POSTGRESQL

spring.jpa.hibernate.ddl-auto :  update
spring.jpa.hibernate.naming_strategy :  org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.show-sql :  true

spring.thymeleaf.cache :  false
spring.thymeleaf.enabled :  true
server.port  :  9090

flyway.enabled : true

spring.data.rest.base-uri : /api

spring.rabbitmq.host : localhost
spring.rabbitmq.port : 5672
spring.rabbitmq.username : admin
spring.rabbitmq.password : localhost

spring.redis.host : localhost
spring.redis.port : 6379

logging.level.org.springframework : INFO
logging.file : logging.log

security.user.role[0] :  SUPER_ADMIN
security.user.role[1] :  STUDENT
security.user.role[2] :  PIC
security.user.role[3] :  REGISTRANT
security.user.role[4] :  FINANCIAL_STAFF
security.user.role[5] :  FINANCIAL_MANAGER

security-util:
   role-prefix:
       SUPER_ADMIN: SADM-
       STUDENT : STUD-
       PIC : PICH-
       REGISTRANT : RGST-
       FINANCIAL_STAFF : FIST-
       FINANCIAL_MANAGER : FIMG-

